### ISSUE TITLE
Add twitter feed to homepage

### ISSUE THREAD

**Issue by Spiruel** [satschool-outreach/satschool-outreach.github.io#12]
Embed satschool_ twitter feed into website. Where do we want to put it?

```
<a class="twitter-timeline" href="https://twitter.com/SatSchool_?ref_src=twsrc%5Etfw">
Tweets by SatSchool_
</a> 
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by jconnollyeo** [comment]
I think the "About" page would be good. Or, once we add a "News" page it would make sense to have it there

**Comment by jconnollyeo** [comment]
The News page is now available so you could see if it works on there
