### ISSUE TITLE
Higher res SENSE CDT logo on "Partners" page

### ISSUE THREAD

**Issue by jconnollyeo** [satschool-outreach/satschool-outreach.github.io#6]
The current logo looks pixelated so we need one with a greater resolution. 

![image](https://user-images.githubusercontent.com/73107346/204768384-fc1e28f8-750a-4099-a602-72dd02849cd3.png)

**Comment by Spiruel** [comment]
resolved with #9 

canvas size needs to be 843 x 1043 for future images on this page, otherwise the alignment goes funky
