### ISSUE TITLE
Explore the possibility to make the tiles for each module clickable on the homepage

### ISSUE THREAD

**Issue by jconnollyeo** [satschool-outreach/satschool-outreach.github.io#8]
Can we make the tiles clickable so they link to each respective module?

**Comment by Spiruel** [comment]
You can do this with some simple html, but the bounding boxes cannot be diamond shaped. Maybe it will be OK just using rectangular bounding boxes (or multiple boxes?). Either way, it's certainly possible!

[SatSchool _ SatSchool.html.txt](https://github.com/satschool-outreach/satschool-outreach.github.io/files/10228022/SatSchool._.SatSchool.html.txt)
